### ISSUE TITLE
Can't generate the graph

### ISSUE THREAD

**Issue by cilerler** [KevReed/DocFx.Plugins.PlantUml#7]
Unfortunately it is not working and here is the re-producing steps.

1. create a new folder
2. type `choco install docfx -y` and hit <kbd>Enter</kbd> _(Installed **DocFx** through chocolatey)_
3. type `docfx init -q` and hit <kbd>Enter</kbd>
4. type `cd docfx_project` and hit <kbd>Enter</kbd>
5. type `nuget install DocFx.Plugins.PlantUml -ExcludeVersion -OutputDirectory .` and hit <kbd>Enter</kbd>
6. in **docfx.json** change the part
    ```
    	"template": [
    		"default"
    	],
    ```
    as 
    ```
    	"template": [
    		"default",
    		"DocFx.Plugins.PlantUml/template"
    	],
    ```
7. in **articles/intro.md** add the following part to the bottom
    ~~~
    ```plantUml
    Bob->Alice : hello
    ```
    ~~~
8. type `docfx docfx.json --serve` and hit <kbd>Enter</kbd>
9. wait until you see *Serving "C:\Users\..\docfx_project\_site" on http://localhost:8080* 
10. open your browser and go to http://localhost:8080/articles/intro.html
11. You will not see the graphic you are supposed to see instead you will see a code block

**Comment by mkniller** [comment]
I am having this same issue using the latest stable version of DoxFX, Java, and GraphViz.  Just curious if this project is still being worked on, and if so, is there a workaround to get the diagrams to render?

I have tried both local and remote  rendering.

**Comment by agent00jackson** [comment]
I had the same issue and was able to get around it by using dfm-latest as the markdown engine.

**Comment by cilerler** [comment]
@agent00jackson can you provide step by step instruction how to do it, please?

**Comment by agent00jackson** [comment]
@cilerler 
In your `docfx.json`:
```js
{
  ...
  "build":{
    ...
    "markdownEngineName": "dfm-latest"
  }
}
```
